from . import test_sale_credit_exception
