from . import test_check_so_exceptions
